[package]
name = "zwave-driver"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zwave-serial = { path = "../serial" }
zwave-core = { path = "../core" }
hex = "0.4.3"
tokio = { version = "1.33.0", features = ["rt"] }
thiserror = "1.0.50"
custom_debug_derive = "0.5.1"
