[package]
name = "zwave-driver"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_debug_derive.workspace = true
hex.workspace = true
thiserror.workspace = true
tokio.workspace = true
zwave-core.workspace = true
zwave-serial.workspace = true
