[package]
name = "zwave-driver"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_debug_derive.workspace = true
paste.workspace = true
petgraph.workspace = true
proc-macros.workspace = true
termcolor.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
typed-builder.workspace = true
unique_id.workspace = true
zwave-cc.workspace = true
zwave-core.workspace = true
zwave-logging.workspace = true
zwave-serial.workspace = true
bytes.workspace = true
hex.workspace = true
futures.workspace = true