[package]
name = "zwave-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zwave-serial = { path = "../serial" }
crossbeam = "0.8.2"
hex = "0.4.3"
