[package]
name = "serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
hex = "0.4.3"
serialport = "4.2.2"
crossbeam-channel = "0.5.8"
num-traits = "0.2"
num-derive = "0.3"