[package]
name = "serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
hex = "0.4.3"
serialport = "4.2.2"
crossbeam-channel = "0.5.8"
nom = "7.1.3"
ux = "0.1.5"
paste = "1.0.14"
derive-try-from-primitive = "1.0.0"
bytes = "1.5.0"
