[workspace]
members = ["packages/serial", "packages/cli", "packages/driver", "packages/core"]
resolver = "2"

[workspace.package]
rust-version = "1.76"
edition = "2021"

[profile.release]
strip = true
lto = true
