[workspace]
members = [
	"packages/serial",
	"packages/cli",
	"packages/driver",
	"packages/core",
]
resolver = "2"

[workspace.package]
rust-version = "1.76"
edition = "2021"

[workspace.dependencies]
bitvec = "1.0.1"
bytes = "1.5.0"
cookie-factory = "0.3.2"
custom_debug_derive = "0.5.1"
derive-try-from-primitive = "1.0.0"
enum_dispatch = "0.3.12"
futures = "0.3.29"
hex = "0.4.3"
nom = "7.1.3"
paste = "1.0.14"
serialport = "4.2.2"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = [
	"rt-multi-thread",
	"macros",
	"time",
	"sync",
] }
tokio-serial = "5.4.4"
tokio-util = { version = "0.7.10", features = ["codec"] }
ux = "0.1.5"
zwave-core = { path = "packages/core" }
zwave-driver = { path = "packages/driver" }
zwave-serial = { path = "packages/serial" }

[profile.release]
strip = true
lto = true
