[workspace]
members = [
    "packages/cli",
    "packages/core",
    "packages/driver",
    "packages/proc-macros",
    "packages/serial",
]
resolver = "2"

[workspace.package]
rust-version = "1.76"
edition = "2021"

[workspace.dependencies]
bitflags = "2.4.1"
bitvec = "1.0.1"
bytes = "1.5.0"
cookie-factory = "0.3.2"
custom_debug_derive = "0.5.1"
derive-try-from-primitive = "1.0.0"
enum_dispatch = "0.3.12"
enum-iterator = "1.4.1"
futures = "0.3.29"
hex = "0.4.3"
nom = "7.1.3"
num-traits = "0.2.17"
paste = "1.0.14"
pin-project = "1.1.3"
serialport = "4.2.2"
thiserror = "1.0.50"
time = { version = "0.3.30", features = ["formatting", "macros"] }
tokio = { version = "1.33.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "sync",
] }
tokio-serial = "5.4.4"
tokio-util = { version = "0.7.10", features = ["codec"] }
typed-builder = "0.18.0"
unique_id = "0.1.5"
ux = "0.1.5"
proc-macros = { path = "packages/proc-macros" }
walkdir = "2.4.0"
zwave-core = { path = "packages/core" }
zwave-driver = { path = "packages/driver" }
zwave-serial = { path = "packages/serial" }

[profile.release]
incremental = true
# consider objcopy --compress-debug-sections to reduce binary size
lto = true
# Include minimal debug symbols for better backtraces.
debug = 1
