[package]
name = "zwave-cc"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie-factory.workspace = true
custom_debug_derive.workspace = true
derive-try-from-primitive.workspace = true
enum_dispatch.workspace = true
nom.workspace = true
thiserror.workspace = true
ux.workspace = true
zwave-core.workspace = true
typed-builder.workspace = true
proc-macros.workspace = true
paste.workspace = true
