[package]
name = "zwave-core"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec.workspace = true
cookie-factory.workspace = true
custom_debug_derive.workspace = true
derive-try-from-primitive.workspace = true
hex.workspace = true
nom.workspace = true
paste.workspace = true
thiserror.workspace = true
ux.workspace = true
