[package]
name = "zwave-core"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec.workspace = true
cookie-factory.workspace = true
custom_debug_derive.workspace = true
enum-iterator.workspace = true
nom.workspace = true
num-traits.workspace = true
paste.workspace = true
pin-project.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
ux.workspace = true
typed-builder.workspace = true
proc-macros.workspace = true
