[package]
name = "zwave-core"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie-factory = "0.3.2"
hex = "0.4.3"
nom = "7.1.3"
thiserror = "1.0.50"
custom_debug_derive = "0.5.1"
derive-try-from-primitive = "1.0.0"
paste = "1.0.14"
ux = "0.1.5"
bitvec = "1.0.1"
