[package]
name = "proc-macros"
version = "0.0.0"
# autotests = false
publish = false
rust-version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

# [dev-dependencies]
# trybuild = { version = "1.0.49", features = ["diff"] }

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full", "visit"] }
walkdir.workspace = true
