[package]
name = "cli"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zwave-cc.workspace = true
zwave-core.workspace = true
zwave-driver.workspace = true
zwave-serial.workspace = true
bytes.workspace = true
zwave-logging.workspace = true
termcolor.workspace = true
futures.workspace = true
tokio.workspace = true
anyhow = "1.0.97"
